<?php
// CARPETA DEL PROYECTO
define('MAIN','ravisa');
// REFERENCIA A NIVEL PROYECTO
define('URL','http://172.20.20.56:8080/'.constant('MAIN').'/');
// REFERENCIA A NIVEL IMAGENES DEL SITIO
define('IMG','http://172.20.20.56:8080/'.constant('MAIN').'/public/img/');
// NOMBRE DEL PROYECTO
define('PROYECTO','Ravisa | OnBase 2024');
// FOOTER DE LA PAGINA
define('FOOTER','Ravisa Copyright (©) 2024');
// MOTOR DE BASE
define('HOST','172.20.20.71\SRVSQLONBASE');
// BASE DE DATOS
define('DB','PORTALONBASE');
// USUARIO DE BASE DE DATOS
define('USER','hsi');
// PASSWORD DE USUARIO DE BASE DE DATOS
define('PASSWORD','wstinol');
// CHARSET DE CONEXION (ACENTOS)    
define('CHARSET','utf8mb4');
// COLOR PRIMARIO DE BOTON
define('COLOR_PRIMARIO','#001689');
// COLOR SECUNDARIO DE BOTON
define('COLOR_SECUNDARIO','#134390');
// COLOR S DE BOTON
define('COLOR_TERCIARIO','#D7DBDD');

?>